/**
 * OpenTTD dedicated-server process lifecycle management.
 *
 * 职责: 在隔离 data dir 内生成配置 (openttd.cfg + secrets.cfg), 拉起/停止
 *   dedicated server 子进程, 探活 admin 端口, 保留日志尾。
 * 事实来源 (实测 + 源码):
 *   - OpenTTD 15 把密码放在独立 `secrets.cfg` (`[network]` 下 `admin_password`),
 *     不在 openttd.cfg 的 [network] 段 —— AdminAuthenticationConfigured()
 *     只查 secrets (settings_type.h line 441)。
 *   - `-D host:port -t year -G seed -v dedicated -s null -m null` 可 headless
 *     起服并自动生成地图 (已实测)。
 *   - 手写 secrets.cfg 会被 OpenTTD 视为外部文件并在启动时重建清空; 必须先让
 *     OpenTTD 自己生成一次, 再 patch (已实测)。
 * 禁止: 触碰用户全局配置目录; 隐藏 spawn 错误。
 */

import { spawn, type ChildProcess } from "node:child_process";
import { mkdir, writeFile, readFile, access } from "node:fs/promises";
import { createWriteStream, type WriteStream } from "node:fs";
import net from "node:net";
import path from "node:path";
import { ConfigError, type Config } from "../config.js";

export class TimeoutError extends Error {
	constructor(message: string) {
		super(message);
		this.name = "TimeoutError";
	}
}

const LOG_TAIL_LINES = 200;

export class OpenTTDProcessManager {
	/** Optional exit observer (set by caller). */
	onExit?: (code: number | null) => void;

	private cfg: Config;
	private child: ChildProcess | null = null;
	private logTail: string[] = [];
	private logStream: WriteStream | null = null;
	private configReady = false;

	constructor(cfg: Config) {
		this.cfg = cfg;
	}

	get config(): Config {
		return this.cfg;
	}

	/**
	 * Idempotently prepare the sandbox dir. If no config exists yet, generate it
	 * by a brief headless run (so OpenTTD writes its own openttd.cfg/secrets.cfg),
	 * then patch in our network settings + admin_password.
	 *
	 * WHY generate-then-patch (empirically verified): a hand-written secrets.cfg
	 * is treated as foreign and gets regenerated+wiped on startup; one OpenTTD
	 * itself wrote survives patching. Returns the openttd.cfg path.
	 */
	async ensureSandboxConfig(): Promise<string> {
		if (this.configReady) return path.join(this.cfg.dataDir, "openttd.cfg");
		await mkdir(this.cfg.dataDir, { recursive: true });
		const cfgPath = path.join(this.cfg.dataDir, "openttd.cfg");
		const secretsPath = path.join(this.cfg.dataDir, "secrets.cfg");

		let cfgExists = true;
		try {
			await access(cfgPath);
		} catch {
			cfgExists = false;
		}
		if (!cfgExists) {
			await this.generateConfigs(cfgPath);
		}
		await this.patchOpenttdCfg(cfgPath);
		await this.patchSecretsCfg(secretsPath);
		this.configReady = true;
		return cfgPath;
	}

	/**
	 * Start the dedicated server.
	 * @param opts.newGame when false, treat as keep-existing (unused placeholder
	 *   for future save/load; a fresh map is generated by default).
	 */
	async start(_opts: { newGame?: boolean } = {}): Promise<void> {
		await this.ensureSandboxConfig();
		const bin = this.cfg.openttdBinary;
		try {
			await access(bin);
		} catch {
			throw new ConfigError(
				`OpenTTD binary not found at: ${bin}\n` +
					"Set OPENTTD_BINARY to your install path (Steam: .../steamapps/common/OpenTTD/OpenTTD.app/Contents/MacOS/openttd).",
			);
		}

		const cfgPath = path.join(this.cfg.dataDir, "openttd.cfg");
		const args = [
			"-D",
			`${this.cfg.adminHost}:${this.cfg.gamePort}`,
			"-c",
			cfgPath,
			"-t",
			String(this.cfg.startYear),
			"-G",
			String(this.cfg.seed),
			"-v",
			"dedicated",
			"-s",
			"null",
			"-m",
			"null",
		];

		this.logTail = [];
		this.logStream = createWriteStream(path.join(this.cfg.dataDir, "server.log"), { flags: "a" });

		const child = spawn(bin, args, { stdio: ["ignore", "pipe", "pipe"] });
		this.child = child;

		const onData = (chunk: Buffer) => {
			const text = chunk.toString("utf8");
			for (const line of text.split("\n")) {
				if (line.length === 0) continue;
				this.logTail.push(line);
				if (this.logTail.length > LOG_TAIL_LINES) this.logTail.shift();
			}
			this.logStream?.write(text);
		};
		child.stdout?.on("data", onData);
		child.stderr?.on("data", onData);

		child.on("error", (err) => {
			this.logTail.push(`[spawn-error] ${err.message}`);
			this.logStream?.write(`[spawn-error] ${err.message}\n`);
			this.child = null;
		});
		child.on("exit", (code, _signal) => {
			this.logStream?.end();
			this.logStream = null;
			this.child = null;
			this.onExit?.(code);
		});
	}

	isRunning(): boolean {
		return this.child !== null && this.child.exitCode === null && !this.child.killed;
	}

	/** Graceful stop: SIGTERM, escalate to SIGKILL after 8s. */
	async stop(): Promise<void> {
		const child = this.child;
		if (!child || child.exitCode !== null) {
			this.child = null;
			return;
		}
		const exited = new Promise<void>((resolve) => {
			child.once("exit", () => resolve());
		});
		child.kill("SIGTERM");
		const timer = setTimeout(() => {
			if (child.exitCode === null) child.kill("SIGKILL");
		}, 8000);
		await exited;
		clearTimeout(timer);
		this.child = null;
	}

	/** Poll adminHost:adminPort until connectable or timeout. */
	async waitForAdminPort(timeoutMs = 20_000): Promise<void> {
		const deadline = Date.now() + timeoutMs;
		for (;;) {
			if (await this.canConnect()) return;
			if (Date.now() > deadline) {
				throw new TimeoutError(
					`admin port ${this.cfg.adminHost}:${this.cfg.adminPort} not reachable within ${timeoutMs}ms`,
				);
			}
			await sleep(250);
		}
	}

	getLogTail(): string[] {
		return [...this.logTail];
	}

	// -- config generation / patching --------------------------------------

	/** Run the binary briefly headless to generate default configs, then TERM it. */
	private async generateConfigs(cfgPath: string): Promise<void> {
		const bin = this.cfg.openttdBinary;
		try {
			await access(bin);
		} catch {
			throw new ConfigError(
				`OpenTTD binary not found at: ${bin}\n` + "Set OPENTTD_BINARY to your install path.",
			);
		}
		const child = spawn(bin, [
			"-v", "null", "-s", "null", "-m", "null", "-Q",
			"-c", cfgPath,
			"-t", String(this.cfg.startYear),
		]);
		// Wait ~4s for config write then TERM.
		await sleep(4000);
		if (child.exitCode === null && !child.killed) child.kill("SIGTERM");
		await new Promise<void>((resolve) => {
			if (child.exitCode !== null) return resolve();
			child.once("exit", () => resolve());
			setTimeout(() => resolve(), 3000); // safety
		});
	}

	/** Rewrite the [network] section of openttd.cfg with our ports/auth. */
	private async patchOpenttdCfg(cfgPath: string): Promise<void> {
		let text: string;
		try {
			text = await readFile(cfgPath, "utf8");
		} catch {
			text = "";
		}
		const netBlock =
			"[network]\n" +
			`server_name = ${this.cfg.serverName}\n` +
			`server_port = ${this.cfg.gamePort}\n` +
			`server_admin_port = ${this.cfg.adminPort}\n` +
			"server_admin_chat = true\n" +
			"allow_insecure_admin_login = true\n" +
			"server_game_type = local\n" +
			// The harness must be able to UNPAUSE the game itself.
			//
			// Root cause of the "executor stuck at boot" saga (2026-09-12): the
			// GS was demonstrably ticking (3200 script ticks) while the game
			// calendar advanced ONE day in 120 seconds - script ticks moving, the
			// world frozen, which is the signature of a paused game. OpenTTD's own
			// message explains why the unpause did nothing:
			//
			//   "Game cannot be unpaused manually; disable
			//    pause_on_join/min_active_clients."
			//
			// This block REPLACES [network] wholesale. Omitting these two keys made
			// OpenTTD fall back to its default pause_on_join = true, and a server
			// that pauses when someone joins is simply wrong for an autonomous
			// agent: after the pause the console unpause is refused, the world
			// stops, and every downstream symptom (no executor progress, no
			// heartbeat, no date advance) looks like a broken executor.
			"pause_on_join = false\n" +
			"min_active_clients = 0\n";
		const re = /^\[network\][\s\S]*?(?=^\[)/m;
		if (re.test(text)) {
			text = text.replace(re, netBlock);
		} else {
			text = netBlock + "\n" + text;
		}
		await writeFile(cfgPath, text, "utf8");
	}

	/** Set admin_password in secrets.cfg (must be OpenTTD-generated first). */
	private async patchSecretsCfg(secretsPath: string): Promise<void> {
		let text: string;
		try {
			text = await readFile(secretsPath, "utf8");
		} catch {
			// Missing entirely (unexpected after generate): best-effort write.
			text = `[network]\nadmin_password = ${this.cfg.adminPassword}\n`;
		}
		const lineRe = /^admin_password = .*$/m;
		if (lineRe.test(text)) {
			text = text.replace(lineRe, `admin_password = ${this.cfg.adminPassword}`);
		} else {
			text = text.replace(/^\[network\]\n/m, `[network]\nadmin_password = ${this.cfg.adminPassword}\n`);
		}
		await writeFile(secretsPath, text, "utf8");
	}

	// -- private helpers -----------------------------------------------------

	private canConnect(): Promise<boolean> {
		return new Promise((resolve) => {
			const sock = net.connect({ host: this.cfg.adminHost, port: this.cfg.adminPort });
			const done = (ok: boolean) => {
				sock.removeAllListeners();
				sock.destroy();
				resolve(ok);
			};
			sock.once("connect", () => done(true));
			sock.once("error", () => done(false));
			sock.setTimeout(500);
			sock.once("timeout", () => done(false));
		});
	}
}

function sleep(ms: number): Promise<void> {
	return new Promise((r) => setTimeout(r, ms));
}
